#!/usr/bin/bash
export GDK_BACKEND=x11
export LIBGL_ALWAYS_INDIRECT=1
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export SDL_IM_MODULE=fcitx
export INPUT_METHOD=fcitx
export GLFW_IM_MODULE=ibus
export DISPLAY=$(route -n | grep -E '^0\.0\.0\.0' | awk '{print $2}'):5
i3
